name: "Build"
on:
  pull_request:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v4

    - name: Run the Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v2

    - name: Build
      run: |
        nix develop --impure -c make

    - name: Run Tests
      run: |
        nix develop --impure -c make test
