name: "Build"
on:
  pull_request:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Tests
      run: |
        nix run .#test -L --impure

    - name: Build
      run: |
        nix run .#build -L --impure
